version: '3.8'

services:
    laravel:
        image: laravelsail/php80-composer
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=laravel_mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
        networks:
            - laravel
        depends_on:
            - mysql
        command: >
            /bin/bash -c "
            apt-get update && apt-get install -y netcat &&
            echo 'Waiting for MySQL...' &&
            while ! nc -z laravel_mysql 3306; do
              echo 'MySQL is unavailable - sleeping'
              sleep 2
            done &&
            echo 'MySQL is up - executing commands' &&
            php artisan vendor:publish --provider=\"Laravel\\Sanctum\\SanctumServiceProvider\" &&
            php artisan migrate &&
            php artisan serve --host=0.0.0.0 --port=8000
            "

    mysql:
        image: mysql:5.7
        container_name: laravel_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mysql_data:

networks:
    laravel:
